# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290350c7cd0805dd7be98380edcba2478fc15a22aed3183f10863cc1f4aee1a2ade1ea247f9f6c885dd9af70e9a1c089f446b7374a1d0f9cc56e85937a4bdf02

test:
  secret_key_base: fdada7ee06592bb6f6f71a3601f6a9faa21d44f44936cf32c54e285667cf9b268dae474cdad602b58a1df585a69aef154edb4dd9e68f9edb230bdc4691b38cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
